[DEFAULT]
nodes = {clusternodes}
orchestrate = ha

[fs#1]
type = xfs
dev = {env.dev}
mnt = /nfssvc
install = /nfs from ./cfg/{name} key script mode 755 user root group root

[app#0]
script = {fs#1.mnt}/nfs
start = true
stop = true
restart = true

[ip#0]
type = host
name = {env.ip}
netmask = {env.mask}
dev = {env.nic}

[env]
ip = nfs.acme.com
mask = 24
nic = eth0
dev = /dev/mapper/36001405a34fd1374fdc49ac8a0c7883b