[DEFAULT]
nodes = {clusternodes}
orchestrate = ha

[ip#1]
ipname = {env.fqdn}
ipdev = {env.nic}
alias = false
shared = true

[fs#1]
type = ext4
dev = {env.dev}
mnt = /srv/{fqdn}
shared = true
user = root
group = root
perm = 755
post_provision = /bin/bash -c 'mkdir -p /srv/{fqdn}/run/{nfsstate,nfsdcld,nfsdcltrack} /srv/{fqdn}/etc /srv/{fqdn}/nfsroot'

[app#0]
start = mount -t rpc_pipefs sunrpc /var/lib/nfs/rpc_pipefs
stop = umount sunrpc
check = /bin/sh -c 'if mount | grep -w sunrpc > /dev/null 2>&1; then /bin/true; else /bin/false; fi'
disable = true

[app#1]
type = simple
start = /usr/sbin/nfsdcld --foreground
disable = true

[app#2]
type = simple
start = /usr/sbin/rpc.idmapd -f
disable = true

[app#3]
pre_start = /usr/sbin/exportfs -r
start = /usr/sbin/rpc.nfsd {env.nfsthreads}
post_start = /bin/sh -c 'if systemctl -q is-active gssproxy; then systemctl reload gssproxy ; fi'
stop = /usr/sbin/rpc.nfsd 0
post_stop = /bin/sh -c '/usr/sbin/exportfs -au; /usr/sbin/exportfs -f'
check = /bin/sh -c 'if test `ps aux|grep -w [n]fsd|wc -l` -eq {env.nfsthreads}; then /bin/true; else /bin/false; fi'
disable = true

[app#4]
type = simple
start = /usr/sbin/rpc.mountd --foreground
disable = true

[sync#i0]
disable = true

[env]
nfsthreads = 8
dev = /dev/mapper/36001405a34fd1374fdc49ac8a0c7883b
fqdn = nfsv4.acme.com
nic = eth0
