[DEFAULT]
id = 682ac60b-4f10-47a1-b917-df2e4742ae5f
nodes = {clusternodes}
orchestrate = ha

[ip#1]
type = host
name = {env.nfshost}
dev = {env.nic}

[fs#1]
type = ext4
dev = {env.dev}
mnt = {env.rootfs}
install = 
 /run/nfsstate/
 /run/nfsdcld/
 /run/nfsdcltrack/
 /run/nfsstate/
 /etc/
 /nfsroot/
 /init/nfsd from ./cfg/{name} source {env.templates}/nfs/init.nfsd template mode 755
 /etc/nfs.conf from ./cfg/{name} source {env.templates}/nfs/etc.nfs.conf template
 /etc/exports from ./cfg/{name} source {env.templates}/nfs/etc.exports.conf template
shared = true

[fs#2]
type = rpc_pipefs
mnt = /var/lib/nfs/rpc_pipefs
shared = true

[fs#3]
type = bind
dev = {env.rootfs}/etc/nfs.conf
mnt = /etc/nfs.conf
shared = true

[fs#4]
type = bind
dev = {env.rootfs}/etc/exports
mnt = /etc/exports
shared = true

[app#1]
type = simple
start = /usr/sbin/nfsdcld --foreground
desc = nfsdcld
shared = true

[app#2]
type = simple
start = /usr/sbin/rpc.idmapd -f
desc = rpc.idmapd
shared = true

[app#3]
type = forking
start = {env.rootfs}/init/nfsd start
stop = {env.rootfs}/init/nfsd stop
check = {env.rootfs}/init/nfsd status
desc = nfsd
shared = true

[app#4]
type = simple
start = /usr/sbin/rpc.mountd --foreground
desc = rpc.mountd
shared = true

[env]
dev = /dev/mapper/36001405ded28414e2ea4c248008e6af1
rootfs = /srv/{fqdn}
nfshost = nfsv4.opensvc.com
templates = https://raw.githubusercontent.com/opensvc/opensvc_templates/main

