#!/bin/bash

nfsstart(){
	systemctl start rpcbind
	systemctl start nfs-server
	systemctl start nfs-mountd
	systemctl start nfs-kernel-server
	systemctl start rpc-statd
}

nfsstop(){
	exportfs -ua

	systemctl stop nfs-kernel-server
	systemctl stop nfs-mountd
	systemctl stop nfs-server
	systemctl stop rpc-statd


	pkill -TERM fsidd  2>/dev/null; sleep 1; pkill -KILL fsidd  2>/dev/null
	pkill -TERM nfsdcld 2>/dev/null; sleep 1; pkill -KILL nfsdcld 2>/dev/null
}

case "$1" in
start)
    nfsstart
    ;;
stop)
    nfsstop
    ;;
restart)
    nfsstop
    nfsstart
    ;;
*)
    echo "usage $0 { start | stop | restart }"
    ;;
esac

exit 0